dist: trusty
sudo: required
services:
- docker
language: go

branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      env: GOFLAGS=-mod=vendor GO111MODULE=on
      script:
        - make test
        - make vet
        - make static
        - make website-test
    - go: "1.13.x"
      env: GO111MODULE=on
      script:
        - make test
        - make vet
        - make static
        - make vendor-check
        - make website-test
