mqtt:
  verify_ssl: false

vcd:
  host: "atl1-vcd-static-99-234.eng.vmware.com"
  log: true
  password: "ca$hc0w"
  port: 443
  username: "administrator"
  verify: false

vcs:
  - name: "vc1"
    password: "Welcome@123"
    username: "administrator@vsphere.local"
    verify: false

service:
  enforce_authorization: false
  legacy_mode: false
  log_wire: false
  no_vc_communication_mode: false
  processors: 15
  telemetry:
    enable: true

broker:
  catalog: "cat-cse"
  ip_allocation_mode: pool
  network: "cse_routed_net"
  org: "cse_org"
  remote_template_cookbook_url: https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/template_v2.yaml
  storage_profile: "*"
  vdc: "cse_vdc"