name: check-code
on:
  push:
    paths-ignore:
      - '**.md'
      - 'website/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'website/**'

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: vet
      run: make vet

    - name: static
      run: make static

    - name: test
      run: make test
