name: check-code
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'website/**'

jobs:
  check-replaced-modules:
    name: Check replaced modules
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: check-gomod
        run: ./scripts/check-gomod.sh
