name: Run Gosec
on: [push, pull_request]
jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: gosec
        run: make security
